version: "3"

# Docker compose to use top deploy database in development
# Backend and webapp are expected to be run separately

services:
  image: kunlium/luceweb
    ports:
      - 8001:80
    restart: unless-stopped
  
  ganache_db:
    image: trufflesuite/ganache:v7.7.3
    restart: unless-stopped
    command: -l 300000000 --database.dbPath /ganache_db --chain.chainId 72 -h 0.0.0.0 --wallet.accounts "0xd49df1af2d195c2c56cb4aa9119d188889c8c28c011501a339a1eafcdcb790d8, 1000000000000000000000000" --wallet.accounts "0x56c6de6fd54438dbb31530f5fdeeaada0b1517880c91dfcd46a4e5fec59a9c79, 1000000000000000000000000" "0xcd4fc6fe57bb44764562df4abae6e9673a4b9db250ea94a0a42ac8500e0275eb, 1000000000000000000000000"
    ports:
      - 8545:8545
    # environment:
    #   - VIRTUAL_PORT=8545
    #   - VIRTUAL_HOST=ganache.luce.137.120.31.102.nip.io
    #   - LETSENCRYPT_HOST=ganache.luce.137.120.31.102.nip.io
    volumes:
      - ${STORAGE_PATH:-./data}/ganache_db:/ganache_db

  postgres_db:
    image: postgres
    restart: unless-stopped
    depends_on:
      - ganache_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=luce123456
      - POSTGRES_USER=luce
      - POSTGRES_DB=lucedb
    volumes:
      - ${STORAGE_PATH:-./data}/postgres_db:/var/lib/postgresql/data
      - ./luce_vm/scripts/init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh

  zkp_service:
    build: ./luce_vm/js
    ports:
      - 8888:8888

  # jupyterlab:
  #   # image: jupyter/base-notebook
  #   build: ./luce_vm/jupyter
  #   restart: unless-stopped
  #   user: root
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - ./luce_vm/jupyter:/home/jovyan/work
  #   environment:
  #     - JUPYTER_TOKEN=password
  #     - GRANT_SUDO=yes
  #     - JUPYTER_ENABLE_LAB=yes

  # ethereum-node:
  #   image: ethereum/client-go
  #   ports:
  #     - "30303:30303"
  #   command: "--rpc --rpcaddr 0.0.0.0"
  #   volumes:
  #     - ./data/ethereum:/root/.ethereum
