# Generated by Django 4.1.12 on 2024-02-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=255, unique=True, verbose_name="email address")),
                ("country", models.CharField(max_length=25, null=True)),
                ("institution", models.CharField(max_length=255, null=True)),
                ("ethereum_private_key", models.CharField(blank=True, max_length=255, null=True)),
                ("ethereum_public_key", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("is_approved", models.BooleanField(blank=True, default=True, null=True)),
                ("user_type", models.IntegerField(choices=[(0, "Data Provider"), (1, "Data Requester")], null=True)),
                ("active", models.BooleanField(default=True)),
                ("staff", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
                ("gender", models.CharField(choices=[(0, "Male"), (1, "Female")], max_length=6, null=True)),
                ("age", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
